server:
  port: 9091

# datasource properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Musaddil@l3108
    url: jdbc:mysql://localhost:3306/jrtp
    username: root
# to create table in the database(in not already created)    
  jpa:
    hibernate:
      ddl-auto: update
 # to show sql quries      
    show-sql: true
    
    
 #SMTP proprerties for mail sending   
  mail:
    host: smtp.gmail.com
    password: jojg nlry knbb wndv
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ayush.chibu@gmail.com
    
    
#Application messages
app:
    messages:         #messages can be considered as a Map (key-value)
      invalidLogin: Invalid Credentials
      invalidPwds: Password not same
      pwdNotUpdate: Pwd update failed
      regSeccess: Registration successfull
      regFail: Registration failed
      quoteUrl: https://type.fit/api/quotes;
      restPwd: Reset Password - Ayush IT
      pwdCharacters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()-_=+
      
      
      