server:
  port: 9091

# Datasource properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# SMTP properties for mail sending
  mail:
    host: smtp.gmail.com
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${MAIL_USERNAME}

# Application messages
app:
  messages:
    invalidLogin: Invalid Credentials
    invalidPwds: Passwords do not match
    pwdNotUpdate: Password update failed
    regSuccess: Registration successful
    regFail: Registration failed
    quoteUrl: https://type.fit/api/quotes
    resetPwd: Reset Password - Ayush IT
    pwdCharacters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()-_=+

